### ISSUE TITLE
Issue with the explorer setting up

### ISSUE THREAD

**Issue by guardawallet** [trxplorer/explorer#3]
Hi team! 
I am from Guarda.co. We would like to add TRON into all Guarda wallets, but we've faced with setting up your explorer. 
When executing `mvn install` in a cloned repository, the following error occurs:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:tron-cli:jar:1.0.73-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:model:jar:1.0.73-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:sql-maven-plugin is missing. @ io.trxplorer:model:[unknown-version], /home/tron/explorer/model/pom.xml, line 113, column 14
[WARNING] 'build.plugins.plugin.version' for io.fabric8:docker-maven-plugin is missing. @ io.trxplorer:model:[unknown-version], /home/tron/explorer/model/pom.xml, line 63, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:syncnode:jar:1.0.73-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:syncnode:[unknown-version], /home/tron/explorer/sync-node/pom.xml, line 180, column 15
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.mashape.unirest:unirest-java:jar -> duplicate declaration of version 1.4.9 @ io.trxplorer:syncnode:[unknown-version], /home/tron/explorer/sync-node/pom.xml, line 192, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:searchengine:jar:1.0.73-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:searchengine:[unknown-version], /home/tron/explorer/search-engine/pom.xml, line 198, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:service:jar:1.0.73-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:api-server:jar:1.0.73-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:api-server:[unknown-version], /home/tron/explorer/api-server/pom.xml, line 174, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:webapp:jar:1.0.73-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:webapp:[unknown-version], /home/tron/explorer/webapp/pom.xml, line 156, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trxplorer:parent:pom:1.0.73-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 122, column 19
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Parent
[INFO] Tron client
[INFO] Model
[INFO] SyncNode
[INFO] Seach Engine
[INFO] Service
[INFO] Api Server
[INFO] Webapp
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Parent 1.0.73-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ parent ---
[INFO] Installing /home/tron/explorer/pom.xml to /home/tron/.m2/repository/io/trxplorer/parent/1.0.73-SNAPSHOT/parent-1.0.73-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Tron client 1.0.73-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tron-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/tron/explorer/tron-cli/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ tron-cli ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tron-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/tron/explorer/tron-cli/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ tron-cli ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tron-cli ---
[INFO] Surefire report directory: /home/tron/explorer/tron-cli/target/surefire-reports
```

T E S T S
```
Running io.trxplorer.troncli.TronCliTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/tron/.m2/repository/io/netty/netty-common/4.1.17.Final/netty-common-4.1.17.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
360
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.797 sec <<< FAILURE!
testSolidityNodeCli(io.trxplorer.troncli.TronCliTest) Time elapsed: 30.65 sec <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
at org.tron.api.WalletSolidityGrpc$WalletSolidityBlockingStub.getNowBlock(WalletSolidityGrpc.java:874)
at io.trxplorer.troncli.TronSolidityNodeCli.getLastBlock(TronSolidityNodeCli.java:95)
at io.trxplorer.troncli.TronCliTest.testSolidityNodeCli(TronCliTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /47.89.244.227:50051
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
at java.base/java.lang.Thread.run(Thread.java:844)

Results :

Tests in error:
testSolidityNodeCli(io.trxplorer.troncli.TronCliTest): UNAVAILABLE: io exception

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent ............................................. SUCCESS [ 0.281 s]
[INFO] Tron client ........................................ FAILURE [ 32.607 s]
[INFO] Model .............................................. SKIPPED
[INFO] SyncNode ........................................... SKIPPED
[INFO] Seach Engine ....................................... SKIPPED
[INFO] Service ............................................ SKIPPED
[INFO] Api Server ......................................... SKIPPED
[INFO] Webapp ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.150 s
[INFO] Finished at: 2019-01-16T15:51:14+01:00
[INFO] Final Memory: 16M/68M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tron-cli: There are test failures.
[ERROR]
[ERROR] Please refer to /home/tron/explorer/tron-cli/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn <goals> -rf :tron-cli
```

Our environment: 
OS - Ubuntu 18.04.1 LTS

Java
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Maven
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 10.0.2, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-38-generic", arch: "amd64", family: "unix"

Could you please help us to realise where the issue could be localised?

**Comment by Tillliende** [comment]
> Hi team!
> I am from Guarda.co. We would like to add TRON into all Guarda wallets, but we've faced with setting up your explorer.
> When executing `mvn install` in a cloned repository, the following error occurs:
> 
> ```
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:tron-cli:jar:1.0.73-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:model:jar:1.0.73-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:sql-maven-plugin is missing. @ io.trxplorer:model:[unknown-version], /home/tron/explorer/model/pom.xml, line 113, column 14
> [WARNING] 'build.plugins.plugin.version' for io.fabric8:docker-maven-plugin is missing. @ io.trxplorer:model:[unknown-version], /home/tron/explorer/model/pom.xml, line 63, column 14
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:syncnode:jar:1.0.73-SNAPSHOT
> [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:syncnode:[unknown-version], /home/tron/explorer/sync-node/pom.xml, line 180, column 15
> [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.mashape.unirest:unirest-java:jar -> duplicate declaration of version 1.4.9 @ io.trxplorer:syncnode:[unknown-version], /home/tron/explorer/sync-node/pom.xml, line 192, column 15
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:searchengine:jar:1.0.73-SNAPSHOT
> [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:searchengine:[unknown-version], /home/tron/explorer/search-engine/pom.xml, line 198, column 15
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:service:jar:1.0.73-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:api-server:jar:1.0.73-SNAPSHOT
> [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:api-server:[unknown-version], /home/tron/explorer/api-server/pom.xml, line 174, column 15
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:webapp:jar:1.0.73-SNAPSHOT
> [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jooby:jooby-commons-email:jar -> duplicate declaration of version (?) @ io.trxplorer:webapp:[unknown-version], /home/tron/explorer/webapp/pom.xml, line 156, column 15
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 680, column 14
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ io.trxplorer:parent:1.0.73-SNAPSHOT, /home/tron/explorer/pom.xml, line 122, column 19
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for io.trxplorer:parent:pom:1.0.73-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 122, column 19
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO]
> [INFO] Parent
> [INFO] Tron client
> [INFO] Model
> [INFO] SyncNode
> [INFO] Seach Engine
> [INFO] Service
> [INFO] Api Server
> [INFO] Webapp
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Parent 1.0.73-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-install-plugin:2.4:install (default-install) @ parent ---
> [INFO] Installing /home/tron/explorer/pom.xml to /home/tron/.m2/repository/io/trxplorer/parent/1.0.73-SNAPSHOT/parent-1.0.73-SNAPSHOT.pom
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Tron client 1.0.73-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tron-cli ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/tron/explorer/tron-cli/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ tron-cli ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tron-cli ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/tron/explorer/tron-cli/src/test/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ tron-cli ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tron-cli ---
> [INFO] Surefire report directory: /home/tron/explorer/tron-cli/target/surefire-reports
> ```
> 
> T E S T S
> 
> ```
> Running io.trxplorer.troncli.TronCliTest
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/tron/.m2/repository/io/netty/netty-common/4.1.17.Final/netty-common-4.1.17.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
> WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 360
> Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.797 sec <<< FAILURE!
> testSolidityNodeCli(io.trxplorer.troncli.TronCliTest) Time elapsed: 30.65 sec <<< ERROR!
> io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
> at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
> at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
> at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
> at org.tron.api.WalletSolidityGrpc$WalletSolidityBlockingStub.getNowBlock(WalletSolidityGrpc.java:874)
> at io.trxplorer.troncli.TronSolidityNodeCli.getLastBlock(TronSolidityNodeCli.java:95)
> at io.trxplorer.troncli.TronCliTest.testSolidityNodeCli(TronCliTest.java:24)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
> Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /47.89.244.227:50051
> at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
> at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> at java.base/java.lang.Thread.run(Thread.java:844)
> 
> Results :
> 
> Tests in error:
> testSolidityNodeCli(io.trxplorer.troncli.TronCliTest): UNAVAILABLE: io exception
> 
> Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Parent ............................................. SUCCESS [ 0.281 s]
> [INFO] Tron client ........................................ FAILURE [ 32.607 s]
> [INFO] Model .............................................. SKIPPED
> [INFO] SyncNode ........................................... SKIPPED
> [INFO] Seach Engine ....................................... SKIPPED
> [INFO] Service ............................................ SKIPPED
> [INFO] Api Server ......................................... SKIPPED
> [INFO] Webapp ............................................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 33.150 s
> [INFO] Finished at: 2019-01-16T15:51:14+01:00
> [INFO] Final Memory: 16M/68M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tron-cli: There are test failures.
> [ERROR]
> [ERROR] Please refer to /home/tron/explorer/tron-cli/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn <goals> -rf :tron-cli
> ```
> 
> Our environment:
> OS - Ubuntu 18.04.1 LTS
> 
> Java
> openjdk 10.0.2 2018-07-17
> OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
> OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
> 
> Maven
> Apache Maven 3.5.2
> Maven home: /usr/share/maven
> Java version: 10.0.2, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-11-openjdk-amd64
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "4.15.0-38-generic", arch: "amd64", family: "unix"
> 
> Could you please help us to realise where the issue could be localised?

Near

**Comment by Tillliende** [comment]
.
